import type { MessageCatalog } from "./types";

export const messages = {
  en: {
    authors: { description: "People sharing open roles through GitHub communities.", github: "Open GitHub profile", latestActivity: "Latest activity", open: "View author", profileTitle: "Author", searchPlaceholder: "Search authors or handles", share: "Share author", title: "Authors" },
    common: { all: "All", apply: "Show results", clear: "Clear", close: "Close", filters: "Filters", github: "Open on GitHub", incremental: "Loading the complete catalog…", loading: "Loading public data…", loadMore: "Load more", location: "Location", noResults: "No results match these filters.", offline: "You appear to be offline. Reconnect to load the public catalog.", refresh: "Refresh", results: "results", retry: "Try again", search: "Search", share: "Share", sortCount: "Most jobs", sortName: "Name", sortRecent: "Most recent", sourceError: "The public Openings data could not be loaded." },
    communities: { active: "Active", allSources: "All sources", description: "GitHub communities that publish open tech roles.", errors: "With errors", github: "Open repository", latestActivity: "Latest activity", noOpenings: "No openings", open: "View community", profileTitle: "Community", searchPlaceholder: "Search communities or repositories", share: "Share community", title: "Communities" },
    description: "Tech jobs shared by GitHub communities, made easier to discover.",
    errorMessage: "Please try loading Openings again.", errorTitle: "Openings could not start", eyebrow: "Mobile foundation", localeLabel: "Language", retry: "Try again", status: "Foundation ready", title: "Openings",
    jobs: { allSources: "All sources", areas: "Areas", authors: "Authors", countries: "Countries", description: "Open tech roles collected from public GitHub communities.", detailsTitle: "Job details", employmentTypes: "Employment", freshness: "Freshness", languages: "Languages", newBadge: "New", newOnly: "New for you", noDescription: "The source did not provide a description.", oldest: "Oldest", openOriginal: "Open original listing", posted: "Posted", regions: "Regions", repositories: "Communities", salary: "Salary", salaryOnly: "Salary disclosed", save: "Save job", savedOnly: "Saved only", searchPlaceholder: "Role, stack, company, or location", seniority: "Seniority", share: "Share job", similar: "Similar jobs", sortLabel: "Sort", technologies: "Technologies", title: "Jobs", unsave: "Remove saved job", updated: "Updated", updatedSort: "Recently updated", viewDetails: "View details", workModels: "Work model" },
  },
  "pt-BR": {
    authors: { description: "Pessoas que compartilham vagas por comunidades do GitHub.", github: "Abrir perfil no GitHub", latestActivity: "Atividade mais recente", open: "Ver autor", profileTitle: "Autor", searchPlaceholder: "Buscar autores ou usuários", share: "Compartilhar autor", title: "Autores" },
    common: { all: "Todos", apply: "Mostrar resultados", clear: "Limpar", close: "Fechar", filters: "Filtros", github: "Abrir no GitHub", incremental: "Carregando o catálogo completo…", loading: "Carregando dados públicos…", loadMore: "Carregar mais", location: "Localização", noResults: "Nenhum resultado corresponde a estes filtros.", offline: "Parece que você está sem internet. Reconecte para carregar o catálogo público.", refresh: "Atualizar", results: "resultados", retry: "Tentar novamente", search: "Buscar", share: "Compartilhar", sortCount: "Mais vagas", sortName: "Nome", sortRecent: "Mais recentes", sourceError: "Não foi possível carregar os dados públicos do Openings." },
    communities: { active: "Ativas", allSources: "Todas as fontes", description: "Comunidades do GitHub que publicam vagas abertas de tecnologia.", errors: "Com erros", github: "Abrir repositório", latestActivity: "Atividade mais recente", noOpenings: "Sem vagas", open: "Ver comunidade", profileTitle: "Comunidade", searchPlaceholder: "Buscar comunidades ou repositórios", share: "Compartilhar comunidade", title: "Comunidades" },
    description: "Vagas de tecnologia compartilhadas por comunidades do GitHub, mais fáceis de descobrir.",
    errorMessage: "Tente carregar o Openings novamente.", errorTitle: "O Openings não conseguiu iniciar", eyebrow: "Base mobile", localeLabel: "Idioma", retry: "Tentar novamente", status: "A base está pronta", title: "Openings",
    jobs: { allSources: "Todas as fontes", areas: "Áreas", authors: "Autores", countries: "Países", description: "Vagas abertas de tecnologia reunidas de comunidades públicas do GitHub.", detailsTitle: "Detalhes da vaga", employmentTypes: "Contratação", freshness: "Publicação", languages: "Idiomas", newBadge: "Nova", newOnly: "Novas para você", noDescription: "A fonte não forneceu uma descrição.", oldest: "Mais antigas", openOriginal: "Abrir vaga original", posted: "Publicada", regions: "Regiões", repositories: "Comunidades", salary: "Salário", salaryOnly: "Com salário", save: "Salvar vaga", savedOnly: "Somente salvas", searchPlaceholder: "Cargo, stack, empresa ou local", seniority: "Senioridade", share: "Compartilhar vaga", similar: "Vagas semelhantes", sortLabel: "Ordenar", technologies: "Tecnologias", title: "Vagas", unsave: "Remover vaga salva", updated: "Atualizada", updatedSort: "Atualizadas recentemente", viewDetails: "Ver detalhes", workModels: "Modelo de trabalho" },
  },
  es: {
    authors: { description: "Personas que comparten vacantes en comunidades de GitHub.", github: "Abrir perfil de GitHub", latestActivity: "Actividad reciente", open: "Ver autor", profileTitle: "Autor", searchPlaceholder: "Buscar autores o usuarios", share: "Compartir autor", title: "Autores" },
    common: { all: "Todos", apply: "Mostrar resultados", clear: "Limpiar", close: "Cerrar", filters: "Filtros", github: "Abrir en GitHub", incremental: "Cargando el catálogo completo…", loading: "Cargando datos públicos…", loadMore: "Cargar más", location: "Ubicación", noResults: "Ningún resultado coincide con estos filtros.", offline: "Parece que no tienes conexión. Vuelve a conectarte para cargar el catálogo.", refresh: "Actualizar", results: "resultados", retry: "Reintentar", search: "Buscar", share: "Compartir", sortCount: "Más empleos", sortName: "Nombre", sortRecent: "Más recientes", sourceError: "No se pudieron cargar los datos públicos de Openings." },
    communities: { active: "Activas", allSources: "Todas las fuentes", description: "Comunidades de GitHub que publican empleos tecnológicos.", errors: "Con errores", github: "Abrir repositorio", latestActivity: "Actividad reciente", noOpenings: "Sin vacantes", open: "Ver comunidad", profileTitle: "Comunidad", searchPlaceholder: "Buscar comunidades o repositorios", share: "Compartir comunidad", title: "Comunidades" },
    description: "Empleos de tecnología compartidos por comunidades de GitHub, más fáciles de descubrir.",
    errorMessage: "Intenta cargar Openings de nuevo.", errorTitle: "Openings no pudo iniciarse", eyebrow: "Base móvil", localeLabel: "Idioma", retry: "Intentar de nuevo", status: "La base está lista", title: "Openings",
    jobs: { allSources: "Todas las fuentes", areas: "Áreas", authors: "Autores", countries: "Países", description: "Empleos tecnológicos abiertos de comunidades públicas de GitHub.", detailsTitle: "Detalles del empleo", employmentTypes: "Contratación", freshness: "Publicación", languages: "Idiomas", newBadge: "Nuevo", newOnly: "Nuevos para ti", noDescription: "La fuente no proporcionó una descripción.", oldest: "Más antiguos", openOriginal: "Abrir publicación original", posted: "Publicado", regions: "Regiones", repositories: "Comunidades", salary: "Salario", salaryOnly: "Con salario", save: "Guardar empleo", savedOnly: "Solo guardados", searchPlaceholder: "Puesto, stack, empresa o ubicación", seniority: "Experiencia", share: "Compartir empleo", similar: "Empleos similares", sortLabel: "Ordenar", technologies: "Tecnologías", title: "Empleos", unsave: "Quitar guardado", updated: "Actualizado", updatedSort: "Actualizados recientemente", viewDetails: "Ver detalles", workModels: "Modalidad" },
  },
  it: {
    authors: { description: "Persone che condividono ruoli nelle community GitHub.", github: "Apri profilo GitHub", latestActivity: "Attività recente", open: "Vedi autore", profileTitle: "Autore", searchPlaceholder: "Cerca autori o handle", share: "Condividi autore", title: "Autori" },
    common: { all: "Tutti", apply: "Mostra risultati", clear: "Cancella", close: "Chiudi", filters: "Filtri", github: "Apri su GitHub", incremental: "Caricamento del catalogo completo…", loading: "Caricamento dati pubblici…", loadMore: "Carica altro", location: "Località", noResults: "Nessun risultato corrisponde ai filtri.", offline: "Sembra che tu sia offline. Riconnettiti per caricare il catalogo pubblico.", refresh: "Aggiorna", results: "risultati", retry: "Riprova", search: "Cerca", share: "Condividi", sortCount: "Più offerte", sortName: "Nome", sortRecent: "Più recenti", sourceError: "Impossibile caricare i dati pubblici di Openings." },
    communities: { active: "Attive", allSources: "Tutte le fonti", description: "Community GitHub che pubblicano ruoli tech aperti.", errors: "Con errori", github: "Apri repository", latestActivity: "Attività recente", noOpenings: "Nessuna offerta", open: "Vedi community", profileTitle: "Community", searchPlaceholder: "Cerca community o repository", share: "Condividi community", title: "Community" },
    description: "Offerte di lavoro tech condivise dalle community GitHub, più facili da trovare.",
    errorMessage: "Prova a caricare di nuovo Openings.", errorTitle: "Openings non è riuscito ad avviarsi", eyebrow: "Base mobile", localeLabel: "Lingua", retry: "Riprova", status: "La base è pronta", title: "Openings",
    jobs: { allSources: "Tutte le fonti", areas: "Aree", authors: "Autori", countries: "Paesi", description: "Ruoli tech aperti raccolti da community GitHub pubbliche.", detailsTitle: "Dettagli del lavoro", employmentTypes: "Contratto", freshness: "Pubblicazione", languages: "Lingue", newBadge: "Nuovo", newOnly: "Nuovi per te", noDescription: "La fonte non ha fornito una descrizione.", oldest: "Meno recenti", openOriginal: "Apri annuncio originale", posted: "Pubblicato", regions: "Regioni", repositories: "Community", salary: "Stipendio", salaryOnly: "Con stipendio", save: "Salva lavoro", savedOnly: "Solo salvati", searchPlaceholder: "Ruolo, stack, azienda o località", seniority: "Esperienza", share: "Condividi lavoro", similar: "Lavori simili", sortLabel: "Ordina", technologies: "Tecnologie", title: "Lavori", unsave: "Rimuovi salvataggio", updated: "Aggiornato", updatedSort: "Aggiornati di recente", viewDetails: "Vedi dettagli", workModels: "Modalità" },
  },
  fr: {
    authors: { description: "Les personnes qui partagent des postes via GitHub.", github: "Ouvrir le profil GitHub", latestActivity: "Activité récente", open: "Voir l’auteur", profileTitle: "Auteur", searchPlaceholder: "Rechercher des auteurs", share: "Partager l’auteur", title: "Auteurs" },
    common: { all: "Tous", apply: "Afficher les résultats", clear: "Effacer", close: "Fermer", filters: "Filtres", github: "Ouvrir sur GitHub", incremental: "Chargement du catalogue complet…", loading: "Chargement des données publiques…", loadMore: "Charger plus", location: "Localisation", noResults: "Aucun résultat ne correspond aux filtres.", offline: "Vous semblez hors ligne. Reconnectez-vous pour charger le catalogue public.", refresh: "Actualiser", results: "résultats", retry: "Réessayer", search: "Rechercher", share: "Partager", sortCount: "Plus d’offres", sortName: "Nom", sortRecent: "Plus récentes", sourceError: "Les données publiques d’Openings n’ont pas pu être chargées." },
    communities: { active: "Actives", allSources: "Toutes les sources", description: "Communautés GitHub publiant des postes tech ouverts.", errors: "Avec erreurs", github: "Ouvrir le dépôt", latestActivity: "Activité récente", noOpenings: "Aucune offre", open: "Voir la communauté", profileTitle: "Communauté", searchPlaceholder: "Rechercher communautés ou dépôts", share: "Partager la communauté", title: "Communautés" },
    description: "Des offres tech partagées par les communautés GitHub, plus faciles à découvrir.",
    errorMessage: "Essayez de charger Openings à nouveau.", errorTitle: "Openings n’a pas pu démarrer", eyebrow: "Base mobile", localeLabel: "Langue", retry: "Réessayer", status: "La base est prête", title: "Openings",
    jobs: { allSources: "Toutes les sources", areas: "Domaines", authors: "Auteurs", countries: "Pays", description: "Postes tech ouverts issus de communautés GitHub publiques.", detailsTitle: "Détails du poste", employmentTypes: "Contrat", freshness: "Publication", languages: "Langues", newBadge: "Nouveau", newOnly: "Nouveaux pour vous", noDescription: "La source n’a pas fourni de description.", oldest: "Plus anciens", openOriginal: "Ouvrir l’annonce originale", posted: "Publié", regions: "Régions", repositories: "Communautés", salary: "Salaire", salaryOnly: "Avec salaire", save: "Enregistrer", savedOnly: "Enregistrés seulement", searchPlaceholder: "Poste, stack, entreprise ou lieu", seniority: "Expérience", share: "Partager le poste", similar: "Postes similaires", sortLabel: "Trier", technologies: "Technologies", title: "Offres", unsave: "Retirer des favoris", updated: "Mis à jour", updatedSort: "Récemment mis à jour", viewDetails: "Voir les détails", workModels: "Mode de travail" },
  },
  de: {
    authors: { description: "Menschen, die Stellen über GitHub-Communitys teilen.", github: "GitHub-Profil öffnen", latestActivity: "Letzte Aktivität", open: "Autor ansehen", profileTitle: "Autor", searchPlaceholder: "Autoren oder Handles suchen", share: "Autor teilen", title: "Autoren" },
    common: { all: "Alle", apply: "Ergebnisse anzeigen", clear: "Löschen", close: "Schließen", filters: "Filter", github: "Auf GitHub öffnen", incremental: "Vollständiger Katalog wird geladen…", loading: "Öffentliche Daten werden geladen…", loadMore: "Mehr laden", location: "Standort", noResults: "Keine Ergebnisse entsprechen diesen Filtern.", offline: "Du scheinst offline zu sein. Stelle die Verbindung wieder her, um den Katalog zu laden.", refresh: "Aktualisieren", results: "Ergebnisse", retry: "Erneut versuchen", search: "Suchen", share: "Teilen", sortCount: "Meiste Stellen", sortName: "Name", sortRecent: "Neueste", sourceError: "Die öffentlichen Openings-Daten konnten nicht geladen werden." },
    communities: { active: "Aktiv", allSources: "Alle Quellen", description: "GitHub-Communitys mit offenen Tech-Stellen.", errors: "Mit Fehlern", github: "Repository öffnen", latestActivity: "Letzte Aktivität", noOpenings: "Keine Stellen", open: "Community ansehen", profileTitle: "Community", searchPlaceholder: "Communitys oder Repositorys suchen", share: "Community teilen", title: "Communitys" },
    description: "Tech-Stellen aus GitHub-Communitys, einfacher zu entdecken.",
    errorMessage: "Bitte lade Openings erneut.", errorTitle: "Openings konnte nicht gestartet werden", eyebrow: "Mobile Grundlage", localeLabel: "Sprache", retry: "Erneut versuchen", status: "Die Grundlage ist bereit", title: "Openings",
    jobs: { allSources: "Alle Quellen", areas: "Bereiche", authors: "Autoren", countries: "Länder", description: "Offene Tech-Stellen aus öffentlichen GitHub-Communitys.", detailsTitle: "Stellendetails", employmentTypes: "Anstellung", freshness: "Aktualität", languages: "Sprachen", newBadge: "Neu", newOnly: "Neu für dich", noDescription: "Die Quelle enthält keine Beschreibung.", oldest: "Älteste", openOriginal: "Originalanzeige öffnen", posted: "Veröffentlicht", regions: "Regionen", repositories: "Communitys", salary: "Gehalt", salaryOnly: "Mit Gehalt", save: "Stelle speichern", savedOnly: "Nur gespeichert", searchPlaceholder: "Rolle, Stack, Firma oder Standort", seniority: "Erfahrung", share: "Stelle teilen", similar: "Ähnliche Stellen", sortLabel: "Sortieren", technologies: "Technologien", title: "Stellen", unsave: "Speicherung entfernen", updated: "Aktualisiert", updatedSort: "Kürzlich aktualisiert", viewDetails: "Details ansehen", workModels: "Arbeitsmodell" },
  },
} as const satisfies MessageCatalog;
